### ISSUE TITLE
Accept path to have more than one argument

### ISSUE THREAD

**Issue by dgrr** [Manuel030/dev-radars#1]
Hello,

I'd like to run `dev-radars` like this: `dev-radars -p ~/Project/whatever -p ~/Project/another -p ~/Project/yes`.
Because I have multiple folders under the same project.

Thanks. Nice project btw

**Comment by Manuel030** [comment]
hey @dgrr, you can just give the path to your most top level folder and it parses any subfolders. Does this work for your use case?

**Comment by dgrr** [comment]
No, it doesn't. I have other folders inside of old projects I don't wanna count

**Comment by Manuel030** [comment]
solved in version 0.1.2 by commit 05f0958849bcf2fbfbfe17fe1fdba0e3b868a550
